### PR TITLE
Fix segfault when calling "i3 -C".

### LINKED ISSUE #2144: "-C" switch causes segfault
`i3 -C` causes a segfault because of 287a0b4c3cc24a18f5063b7d5743f0b85d6852a1

@Alexis211 FYI.

i3 4.11

### PR DESCRIPTION
**Pull request by Airblader**
Commit 287a0b4 introduced a segfault when validating the i3 config
as the root_screen will not be set in this case, causing a null
pointer dereference.

fixes #2144

### CODE REVIEW

**Comment by Airblader** [comment]
Putting it on `waiting` until I've also added a test.

**Comment by Airblader** [comment]
OK, I've added a test now.

**Comment by Airblader** [comment]
@stapelberg And now with passing tests.

File: testcases/lib/SocketActivation.pm [hunk 1]
```diff
@@ -96,8 +96,12 @@ sub activate_i3 {
         # the interactive signalhandler to make it crash immediately instead.
         # Also disable logging to SHM since we redirect the logs anyways.
         # Force Xinerama because we use Xdmx for multi-monitor tests.
-        my $i3cmd = abs_path("../i3") . q| -V -d all --disable-signalhandler| .
-                                        q| --shmlog-size=0 --force-xinerama|;
+        my $i3cmd = abs_path("../i3") . q| --shmlog-size=0 --disable-signalhandler|;
+        if (!$args{validate}) {
+            # We only do these if i3 is actually started, but not if -C is passed,
+            # since this contains nothing useful for us in this case.
+            $i3cmd .= q| -V -d all --force-xinerama|;
```
Comment (Airblader) [inline testcases/lib/SocketActivation.pm]: The reasoning for putting `--force-xinerama` in here is that it causes an error to be logged.

File: testcases/t/262-config-validation.t [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+invalid
+EOT
+
+my $pid = launch_with_config($config, validate => 1);
+my $log = get_i3_log;
+
+# We don't care so much about the output (there are tests for this), but rather
+# that we got correct output at all instead of, e.g., a segfault.
+ok($log =~ /Expected one of these tokens/, 'an invalid config token was found');
```
Comment (Airblader) [inline testcases/t/262-config-validation.t]: I'll admit that this isn't perfect, but at least an improvement.

File: testcases/lib/SocketActivation.pm (hunk 1 above)
Comment (stapelberg) [inline testcases/lib/SocketActivation.pm]: Can you make the comment a bit more specific? I.e., can you replace “do these” and “this” with what they refer to? I’m having a bit of trouble following them from just glancing over the diff, and I think that’s the level of understanding that we should aim for with commits :).

File: testcases/lib/SocketActivation.pm [hunk 3]
```diff
@@ -96,8 +96,12 @@ sub activate_i3 {
         # the interactive signalhandler to make it crash immediately instead.
         # Also disable logging to SHM since we redirect the logs anyways.
         # Force Xinerama because we use Xdmx for multi-monitor tests.
-        my $i3cmd = abs_path("../i3") . q| -V -d all --disable-signalhandler| .
-                                        q| --shmlog-size=0 --force-xinerama|;
+        my $i3cmd = abs_path("../i3") . q| --shmlog-size=0 --disable-signalhandler|;
+        if (!$args{validate}) {
```
Comment (stapelberg) [inline testcases/lib/SocketActivation.pm]: Maybe s/validate/validate_config/ for clarity?

File: testcases/lib/i3test.pm [hunk 4]
```diff
@@ -857,8 +859,21 @@ sub launch_with_config {
...
+    # If we called i3 with -C, we wait for it to exit and then return as
+    # there's nothing else we need to do.
+    if ($args{validate}) {
+        $cv->recv;
+        waitpid $i3_pid, 0;
+
+        # We need this since exit_gracefully will not be called in this case.
+        undef $i3_pid;
+
+        return undef;
```
Comment (stapelberg) [inline testcases/lib/i3test.pm]: Wouldn’t it make sense to return `$?` (or `${^CHILD_ERROR_NATIVE}` if you prefer the expressive forms) so that we can check the exit code as well?

File: testcases/lib/i3test.pm [hunk 5]
```diff
@@ -871,6 +886,23 @@ sub launch_with_config {
...
 }
 
+=head2 get_i3_log
+
+Returns the content of the log file for the current test.
+
+=cut
+sub get_i3_log {
+    my $logfile = "$ENV{OUTDIR}/i3-log-for-$ENV{TESTNAME}";
+    my $content = do {
```
Comment (stapelberg) [inline testcases/lib/i3test.pm]: Given that this is the third definition of `slurp` in our code base (see testcases/t/171-config-migrate.t and testcases/lib/StartXServer.pm), how about we properly define `slurp` in i3test once and refer to it? :)

**Comment by Airblader** [comment]
@stapelberg Done.

File: testcases/lib/SocketActivation.pm [hunk 6]
```diff
@@ -96,8 +96,14 @@ sub activate_i3 {
         # the interactive signalhandler to make it crash immediately instead.
         # Also disable logging to SHM since we redirect the logs anyways.
         # Force Xinerama because we use Xdmx for multi-monitor tests.
-        my $i3cmd = abs_path("../i3") . q| -V -d all --disable-signalhandler| .
-                                        q| --shmlog-size=0 --force-xinerama|;
+        my $i3cmd = abs_path("../i3") . q| --shmlog-size=0 --disable-signalhandler|;
+        if (!$args{validate_config}) {
+            # We only set logging and force xinerama if i3 is actually started,
```
Comment (stapelberg) [inline testcases/lib/SocketActivation.pm]: I understand the rationale for logging, but isn’t the log file bigger if we don’t specify --force-xinerama, because it will contain an error message about RandR being absent?

File: testcases/complete-run.pl [hunk 7]
```diff
@@ -30,6 +30,7 @@ BEGIN
 
 # these are shipped with the testsuite
 use lib $dirname . 'lib';
+use i3test::Test;
```
Comment (stapelberg) [inline testcases/complete-run.pl]: nit: here and below, use `use i3test::Test qw(slurp);` so that only the `slurp` function is imported.

**Comment by stapelberg** [comment]
Looks good overall.

File: testcases/complete-run.pl (hunk 7 above)
Comment (Airblader) [inline testcases/complete-run.pl]: I tried, but then I get this:

````
plan() doesn't understand slurp at ./complete-run.pl line 33.
BEGIN failed--compilation aborted at ./complete-run.pl line 33.
```

**Comment by Airblader** [comment]
@stapelberg Updated the xinerama thing. See my comment for the `qw` point.

File: testcases/complete-run.pl (hunk 7 above)
Comment (stapelberg) [inline testcases/complete-run.pl]: Indeed. I think that’s because the package is based on Test::Builder::Module. It seems like we don’t have a better place already set up, so how about putting the slurp function into a new `testcases/lib/i3util.pm`?

**Comment by Airblader** [comment]
@stapelberg Done.
