### PR TITLE
Don't refocus on a workspace cleaned up by `workspace_show` during rename (#3228)

### LINKED ISSUE #3228: Renaming an existing workspace to a workspace assigned to the focused output causes a crash
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.15-96-g9314877d (2018-04-03, branch "issue-3208") © 2009 Michael Stapelberg and contributors
```
URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5717929823830016.bz2

**What I did:**

Using a config file containing:
```
# i3 config file (v4)

workspace 5 output fake-1
# I guess it should work with real outputs as well
fake-outputs 800x500+0+0,800x500+800+0,800x500+800+500,800x500+0+500
```

Run the command:

`i3-msg rename workspace 5 to 6, workspace 6, rename workspace 1 to 5`

**What I saw:**

`i3` crashed with the following tracebacks:
```
  i3 git:(issue-3208) ✗ build/i3 -c ~/i3_issue_config                                  
04/05/2018 01:32:09 AM - ERROR: You did not specify required configuration option "font"
=================================================================                                                                      
==8030==ERROR: AddressSanitizer: heap-use-after-free on address 0x614000001e9c at pc 0x55c186a459e3 bp 0x7ffd6eb44bd0 sp 0x7ffd6eb44bc0
READ of size 4 at 0x614000001e9c thread T0                       
    #0 0x55c186a459e2 in con_get_workspace ../../i3/src/con.c:421
    #1 0x55c186a3be38 in cmd_rename_workspace ../../i3/src/commands.c:1996
    #2 0x55c186a3d9b5 in GENERATED_call parser/GENERATED_command_call.h:22
    #3 0x55c186a404da in next_state ../../i3/src/commands_parser.c:185
    #4 0x55c186a41901 in parse_command ../../i3/src/commands_parser.c:346
    #5 0x55c186a7bd49 in handle_run_command ../../i3/src/ipc.c:124
    #6 0x55c186a84030 in ipc_receive_message ../../i3/src/ipc.c:1308
    #7 0x7f74c84344e2 in ev_invoke_pending (/usr/lib/libev.so.4+0x44e2)
    #8 0x7f74c8437ad5 in ev_run (/usr/lib/libev.so.4+0x7ad5)
    #9 0x55c186a8ba8a in ev_loop /usr/include/ev.h:835
    #10 0x55c186a94789 in main ../../i3/src/main.c:964
    #11 0x7f74c7b2ff49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #12 0x55c186a14d69 in _start (/home/ograff/i3/build/i3+0x4dd69)

0x614000001e9c is located 92 bytes inside of 448-byte region [0x614000001e40,0x614000002000)
freed by thread T0 here:
    #0 0x7f74cb34b711 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45
    #1 0x55c186a435dd in con_free ../../i3/src/con.c:96
    #2 0x55c186abeb0c in tree_close_internal ../../i3/src/tree.c:340
    #3 0x55c186ac97b8 in workspace_show ../../i3/src/workspace.c:469
    #4 0x55c186accc35 in workspace_move_to_output ../../i3/src/workspace.c:999
    #5 0x55c186a3be1f in cmd_rename_workspace ../../i3/src/commands.c:1993
    #6 0x55c186a3d9b5 in GENERATED_call parser/GENERATED_command_call.h:22
    #7 0x55c186a404da in next_state ../../i3/src/commands_parser.c:185
    #8 0x55c186a41901 in parse_command ../../i3/src/commands_parser.c:346
    #9 0x55c186a7bd49 in handle_run_command ../../i3/src/ipc.c:124
    #10 0x55c186a84030 in ipc_receive_message ../../i3/src/ipc.c:1308
    #11 0x7f74c84344e2 in ev_invoke_pending (/usr/lib/libev.so.4+0x44e2)

previously allocated by thread T0 here:
    #0 0x7f74cb34bce1 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:70
    #1 0x55c186ae6f02 in scalloc ../../i3/libi3/safewrappers.c:31
    #2 0x55c186a428e6 in con_new_skeleton ../../i3/src/con.c:40
    #3 0x55c186a42f30 in con_new ../../i3/src/con.c:71
    #4 0x55c186ac6eac in workspace_get ../../i3/src/workspace.c:106
    #5 0x55c186ac9a26 in workspace_show_by_name ../../i3/src/workspace.c:512
    #6 0x55c186aa50ee in init_ws_for_output ../../i3/src/randr.c:510
    #7 0x55c186a678d6 in fake_outputs_init ../../i3/src/fake_outputs.c:77
    #8 0x55c186a9249d in main ../../i3/src/main.c:714
    #9 0x7f74c7b2ff49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
```

**What I expected instead:**
Workspace 5 (previously 1) should be added to the workspaces on output `fake-1`, and a new workspace should backfill output `fake-0` if there are no remaining workspaces. If there were multiple workspaces on `fake-0`, the next (not sure how to define "next") workspace on `fake-0` should be displayed.

This issue was originally discovered in [this comment](https://github.com/i3/i3/issues/3208#issuecomment-377612090) on #3208.

### PR DESCRIPTION
**Pull request by ograff**
When moving a workspace to the current output by way of a rename, if the
current workspace is empty, it will be removed by `workspace_show`.
Attempting to restore focus to this removed workspace causes a crash.
Follow the pattern in workspace.c:996 to only restore the original focus if the
original workspace still exists.

Add a test to ensure that the renamed workspace moves to its appropriate
output and that a crash does not occur.

Fixes #3228

### CODE REVIEW

**Comment by ograff** [comment]
Once it completes, https://travis-ci.org/ograff/i3/builds/366972985 should show that the test case fails without the implementation fixes, and the Travis check on this PR passing should show that same test case passing.

File: src/commands.c [hunk 1]
```diff
@@ -1991,6 +1991,7 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
 
     /* By re-attaching, the sort order will be correct afterwards. */
     Con *previously_focused = focused;
+    Con *previously_focused_parent = focused->parent;
```
Comment (orestisf1993) [inline src/commands.c]: I think the variable here doesn't really improve readability since it's used only once

File: testcases/t/522-rename-assigned-workspace.t [hunk 2]
```diff
@@ -94,4 +94,15 @@ cmd 'rename workspace to 5';
 is(get_output_for_workspace('5'), 'fake-0',
     'Renaming the workspace to a workspace assigned to a directional output should not move the workspace');
 
+##########################################################################
+# Renaming a workspace, so that it becomes assigned to the focused
+# output's workspace (and the focused output is empty) should
+# result in the original workspace replacing the originally
+# focused workspace.
+##########################################################################
```
Comment (orestisf1993) [inline testcases/t/522-rename-assigned-workspace.t]: A newline here for consistency :)

File: src/commands.c [hunk 3]
```diff
@@ -2010,16 +2011,27 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
...
         workspace_move_to_output(workspace, target_output);
+        if (previously_focused) {
+            /* NB: We cannot simply work with previously_focused since it might
+            * have been cleaned up by workspace_show() already, depending on the
+            * focus order/number of other workspaces on the output.
+            * Instead, we loop through the available workspaces and only work with
+            * previously_focused if we still find it. */
+            Con *ws = NULL;
+            TAILQ_FOREACH(ws, &(previously_focused_parent->nodes_head), nodes) {
+                if (ws != previously_focused)
```
Comment (orestisf1993) [inline src/commands.c]: The comparison here doesn't make sense. `previously_focused` could be a normal container. I think this whole block only makes sense when `previously_focused` is a workspace because `con_attach` only touches the focus stack of the workspace and the output.

File: src/commands.c (hunk 1 above)
Comment (ograff) [reply src/commands.c]: I think we need to store it because attempting to access the parent field of `previously_focused` after `workspace_show` would result in attempting to access freed memory, right?

File: testcases/t/522-rename-assigned-workspace.t (hunk 2 above)
Comment (ograff) [reply testcases/t/522-rename-assigned-workspace.t]: D'Oh

File: src/commands.c (hunk 3 above)
Comment (orestisf1993) [reply src/commands.c]: But wait `ws` isn't necessarily a workspace here.

File: src/commands.c (hunk 1 above)
Comment (orestisf1993) [reply src/commands.c]: Yeah, my bad, should have read the comment

File: src/commands.c (hunk 3 above)
Comment (ograff) [reply src/commands.c]: Ah, I guess I haven't quite internalized the container structure yet.
I think the comparison is still correct (albeit renaming ws to con), because the goal is to see if the parent of `previously_focused` still contains `previously_focused`, or am I missing something here?

Comment (ograff) [reply src/commands.c]: Oh yes, I see. This issue could arise if and only if the focused container is a workspace.

**Comment by orestisf1993** [comment]
tip: `git commit` has `--fixup` and `--squash` flags and you can then run `git rebase --autosquash -i`. Might be more convenient.

**Comment by ograff** [comment]
Good tip! I've pushed the fixed up versions

File: src/commands.c [hunk 4]
```diff
@@ -2011,15 +2013,36 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
...
-        if (previously_focused)
+        bool can_restore_focus = previously_focused != 0;
+        /* NB: If previously_focused is a workspace we can't
+         * work directly with it since it might have been cleaned up by
+         * workspace_show() already, depending on the
+         * focus order/number of other workspaces on the output.
+         * Instead, we loop through the available workspaces and only focus
+         * previously_focused if we still find it. */
+        if (previously_focused_is_workspace) {
+            Con *con = NULL;
```
Comment (orestisf1993) [inline src/commands.c]: This branch can be made more idiomatic:

```
Con *output, *workspace = NULL;
TAILQ_FOREACH(output, &(croot->nodes_head), nodes) {
    GREP_FIRST(workspace, output_get_content(output), child == previously_focused);
}
can_restore_focus &= (workspace != NULL);
```
you can remove `previously_focused_parent` with this.

(confirm since I didn't compile)

File: src/commands.c [hunk 5]
```diff
@@ -2011,15 +2013,36 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
         }
         workspace_move_to_output(workspace, target_output);
 
-        if (previously_focused)
+        bool can_restore_focus = previously_focused != 0;
```
Comment (orestisf1993) [inline src/commands.c]: compare with NULL since it is a pointer

**Comment by ograff** [comment]
I'll make those changes. Do you have a preference when reviewing towards
fixup commits that are rebased after review is complete, or just ammending
immediately?

**Comment by orestisf1993** [comment]
I like new commits because AFAIK it is the easier way to check what changed since the last review.

**Comment by ograff** [comment]
Changes up, compiled and tested

**Comment by ograff** [comment]
@orestisf1993 I noticed you CC'd me on #3254, did you want me to rebase this on that?

**Comment by orestisf1993** [comment]
No, but the PR is related to the changes you've made so far so you could be interested in it.

File: src/commands.c [hunk 6]
```diff
@@ -2011,15 +2012,30 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
...
+        bool can_restore_focus = previously_focused != NULL;
+        /* NB: If previously_focused is a workspace we can't
+         * work directly with it since it might have been cleaned up by
+         * workspace_show() already, depending on the
+         * focus order/number of other workspaces on the output.
+         * Instead, we loop through the available workspaces and only focus
+         * previously_focused if we still find it. */
+        if (previously_focused_is_workspace) {
+            Con *output, *workspace = NULL;
+            TAILQ_FOREACH(output, &(croot->nodes_head), nodes) {
```
Comment (orestisf1993) [inline src/commands.c]: Sorry for yet another change here but we can minimize the code even more here since we don't need to iterate over each output:

```diff
diff --git a/src/commands.c b/src/commands.c
index 20b1d7a9..7465aa04 100644
--- a/src/commands.c
+++ b/src/commands.c
@@ -1991,7 +1991,7 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
 
     /* By re-attaching, the sort order will be correct afterwards. */
     Con *previously_focused = focused;
-    bool previously_focused_is_workspace = focused->type == CT_WORKSPACE;
+    Con *previously_focused_content = focused->type == CT_WORKSPACE ? focused->parent : NULL;
     Con *parent = workspace->parent;
     con_detach(workspace);
     con_attach(workspace, parent, false);
@@ -2019,11 +2019,9 @@ void cmd_rename_workspace(I3_CMD, const char *old_name, const char *new_name) {
          * focus order/number of other workspaces on the output.
          * Instead, we loop through the available workspaces and only focus
          * previously_focused if we still find it. */
-        if (previously_focused_is_workspace) {
-            Con *output, *workspace = NULL;
-            TAILQ_FOREACH(output, &(croot->nodes_head), nodes) {
-                GREP_FIRST(workspace, output_get_content(output), child == previously_focused);
-            }
+        if (previously_focused_content) {
+            Con *workspace = NULL;
+            GREP_FIRST(workspace, previously_focused_content, child == previously_focused);
             can_restore_focus &= (workspace != NULL);
         }
```

**Comment by ograff** [comment]
Squashed and new changes added. I'll take a look at that other PR!

**Comment by orestisf1993** [comment]
Thank you!
