### PR TITLE
Fix segfault during config validation (#5167)

### LINKED ISSUE #5167: validate configuration file - segfault
## I'm submitting a…
<pre>
[x] Bug
</pre>

## Current Behavior

<pre>
$ gdb i3
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from i3...

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.archlinux.org
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Reading symbols from /home/darren/.cache/debuginfod_client/daf2315d1ae357416f689ef1c15fe1afc49ebea2/debuginfo...
(gdb) r -Cc /tmp/i3.segfault.txt
Starting program: /usr/bin/i3 -Cc /tmp/i3.segfault.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
76    VPCMPEQ (%rdi), %ymm0, %ymm1
(gdb) bt full
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:76
#1  0x00007ffff7888632 in __GI___strdup (s=0x0) at strdup.c:41
        len = <optimized out>
        new = <optimized out>
#2  0x00005555555775c0 in sstrdup (str=<optimized out>) at ../libi3/safewrappers.c:43
        result = <optimized out>
        default_mode = <optimized out>
        file = <optimized out>
        resolved_path = "/tmp/i3.segfault.txt", '\000' <repeats 4075 times>

                        stack = {stack = {{identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}}}

                  ctx = {use_nagbar = false, assume_v4 = false, state = 95, current_match = {error = 0x0, title = 0x0, application = 0x0, class = 0x0, instance = 0x0, mark = 0x0, window_role = 0x0, workspace = 0x0, machine = 0x0, window_type = 4294967295, urgent = U_DONTCHECK, dock = M_NODOCK, id = 0, window_mode = WM_ANY, con_id = 0x0, match_all_windows = false, insert_where = M_HERE, matches = {tqe_next = 0x0, tqe_prev = 0x0}, restart_mode = false}, statelist = {95, 87, 101, 51, 95, 95, 95, 95, 95, 95}, statelist_idx = 1, stack = 0x7fffffffd320, variables = {slh_first = 0x0}, has_errors = false}
        result = 0
        current = 0x5555555eae90
#3  load_configuration (override_configpath=<optimized out>, load_type=C_VALIDATE) at ../src/config.c:282
        default_mode = <optimized out>
        file = <optimized out>
        resolved_path = "/tmp/i3.segfault.txt", '\000' <repeats 4075 times>

                        stack = {stack = {{identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR, val = {str = 0x0, num = 0}}, {identifier = 0x0, type = STACK_STR,--Type <RET> for more, q to quit, c to continue without paging--
 val = {str = 0x0, num = 0}}}}

                  ctx = {use_nagbar = false, assume_v4 = false, state = 95, current_match = {error = 0x0, title = 0x0, application = 0x0, class = 0x0, instance = 0x0, mark = 0x0, window_role = 0x0, workspace = 0x0, machine = 0x0, window_type = 4294967295, urgent = U_DONTCHECK, dock = M_NODOCK, id = 0, window_mode = WM_ANY, con_id = 0x0, match_all_windows = false, insert_where = M_HERE, matches = {tqe_next = 0x0, tqe_prev = 0x0}, restart_mode = false}, statelist = {95, 87, 101, 51, 95, 95, 95, 95, 95, 95}, statelist_idx = 1, stack = 0x7fffffffd320, variables = {slh_first = 0x0}, has_errors = false}
        result = 0
        current = 0x5555555eae90
#4  0x00005555555683f8 in main (argc=3, argv=0x7fffffffe7e8) at ../src/main.c:476
        override_configpath = 0x5555555eaa50 "/tmp/i3.segfault.txt"
        autostart = true
        layout_path = 0x0
        delete_layout_path = false
        disable_randr15 = false
        fake_outputs = 0x0
        disable_signalhandler = false
        only_check_config = true
        replace_wm = false
        option_index = 0
        opt = -1
        _NET_SUPPORTED_cookie = {sequence = <optimized out>}
        _NET_WM_STATE_FULLSCREEN_cookie = {sequence = <optimized out>}
        MANAGER_cookie = {sequence = <optimized out>}
        ipc_socket = <optimized out>
        error = <optimized out>
        greply = <optimized out>
        extreply = <optimized out>
        needs_tree_init = <optimized out>
        pointerreply = <optimized out>
        output = <optimized out>
        ipc_io = <optimized out>
        log_stream_socket_path = <optimized out>
        log_socket = <optimized out>
--Type <RET> for more, q to quit, c to continue without paging--
        xcb_watcher = <optimized out>
        barconfig = <optimized out>

                    long_options = {{name = 0x5555555bc878 "no-autostart", has_arg = 0, flag = 0x0, val = 97}, {name = 0x5555555b4073 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x5555555bc896 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x5555555bc885 "moreversion", has_arg = 0, flag = 0x0, val = 109}, {name = 0x5555555bc891 "more-version", has_arg = 0, flag = 0x0, val = 109}, {name = 0x5555555bc89e "more_version", has_arg = 0, flag = 0x0, val = 109}, {name = 0x5555555bc8ab "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x5555555b51ff "layout", has_arg = 1, flag = 0x0, val = 76}, {name = 0x5555555b51d4 "restart", has_arg = 1, flag = 0x0, val = 0}, {name = 0x5555555b4baa "force-xinerama", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555b4b9a "force_xinerama", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555b4bcb "disable-randr15", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555b4bba "disable_randr15", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555bc210 "disable-signalhandler", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555bc244 "shmlog-size", has_arg = 1, flag = 0x0, val = 0}, {name = 0x5555555bc250 "shmlog_size", has_arg = 1, flag = 0x0, val = 0}, {name = 0x5555555bc226 "get-socketpath", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555bc235 "get_socketpath", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555b4bdc "fake_outputs", has_arg = 1, flag = 0x0, val = 0}, {name = 0x5555555b4bea "fake-outputs", has_arg = 1, flag = 0x0, val = 0}, {name = 0x5555555bd860 "force-old-config-parser-v4.4-only", has_arg = 0, flag = 0x0, val = 0}, {name = 0x5555555b5108 "replace", has_arg = 0, flag = 0x0, val = 114}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        __FUNCTION__ = "main"
(gdb)
(gdb)
</pre>

<pre>
$ valgrind i3 -Cc /tmp/i3.segfault.txt
==9235== Memcheck, a memory error detector
==9235== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==9235== Using Valgrind-3.19.0 and LibVEX; rerun with -h for copyright info
==9235== Command: i3 -Cc /tmp/i3.segfault.txt
==9235==
==9235== Invalid read of size 1
==9235==    at 0x4847D06: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9235==    by 0x4EDF631: strdup (strdup.c:41)
==9235==    by 0x12B5BF: UnknownInlinedFun (safewrappers.c:43)
==9235==    by 0x12B5BF: load_configuration (config.c:282)
==9235==    by 0x11C3F7: main (main.c:476)
==9235==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==9235==
==9235==
==9235== Process terminating with default action of signal 11 (SIGSEGV)
==9235==  Access not within mapped region at address 0x0
==9235==    at 0x4847D06: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==9235==    by 0x4EDF631: strdup (strdup.c:41)
==9235==    by 0x12B5BF: UnknownInlinedFun (safewrappers.c:43)
==9235==    by 0x12B5BF: load_configuration (config.c:282)
==9235==    by 0x11C3F7: main (main.c:476)
==9235==  If you believe this happened as a result of a stack
==9235==  overflow in your program's main thread (unlikely but
==9235==  possible), you can try to increase the size of the
==9235==  main thread stack using the --main-stacksize= flag.
==9235==  The main thread stack size used in this run was 8388608.
==9235==
==9235== HEAP SUMMARY:
==9235==     in use at exit: 57,677 bytes in 309 blocks
==9235==   total heap usage: 423 allocs, 114 frees, 76,512 bytes allocated
==9235==
==9235== LEAK SUMMARY:
==9235==    definitely lost: 0 bytes in 0 blocks
==9235==    indirectly lost: 0 bytes in 0 blocks
==9235==      possibly lost: 0 bytes in 0 blocks
==9235==    still reachable: 55,661 bytes in 288 blocks
==9235==         suppressed: 0 bytes in 0 blocks
==9235== Rerun with --leak-check=full to see details of leaked memory
==9235==
==9235== For lists of detected and suppressed errors, rerun with: -s
==9235== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)
</pre>

## Expected Behavior

exit 0  
empty stdout  
empty stderr  

## Reproduction Instructions

<pre>
$ valgrind i3 -Cc /tmp/i3.segfault.txt
</pre>

## Environment

<pre>
Binary i3 version:  4.21 (2022-09-21) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.21 (2022-09-21) (pid 6694)
Loaded i3 config:
  /tmp/i3_config (main) (last modified: Tue Sep 27 13:41:38 2022, 705 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

## Misc

system

`Linux 5.19.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 24 Sep 2022 18:24:15 +0000 x86_64 GNU/Linux`

/tmp/i3.segfault.txt

<pre>
# i3 config file (v4)
bar {
  i3bar_command /usr/bin/i3bar
}
</pre>

### PR DESCRIPTION
**Pull request by matugol**
A bug was introduced in #5118 in which configs with bar blocks will segfault during validation. They were copying the i3 font which is not set during validation. This PR simply checks that the `load_type` is not validate before copying the font. Fixes #5167.

### CODE REVIEW

File: src/config.c [hunk 1]
```diff
@@ -275,11 +275,13 @@ bool load_configuration(const char *override_configpath, config_load_t load_type
 
     /* Make bar config blocks without a configured font use the i3-wide font. */
     Barconfig *current;
-    TAILQ_FOREACH (current, &barconfigs, configs) {
-        if (current->font != NULL) {
-            continue;
+    if (load_type != C_VALIDATE) {
```
Comment (orestisfl) [inline src/config.c:278]: I wonder if the check should be config.font != NULL to be extra safe

Comment (matugol) [reply src/config.c:278]: Reason I didn't do that is because `load_font` should exit if it fails to load any fallback fonts, so that check might hide some other crashing failure.

**Review by stapelberg — APPROVED** [review]
