### PR TITLE
floating_enable & floating_maybe_reassign_ws changes

### LINKED ISSUE #297: Failure to assign floating window to a ws on the right display
[Originally reported by Merovius <mail@…>]
(Firefox opened a floating window on coordinates around x=400, y=200 (which is my external display) but i3 assigned it to ws 10 (the currently focused ws on the internal display), so it was not shown unless ws 10 was focused on the internal display and an empty ws was focused on the external.

### LINKED ISSUE #452: Window maps on wrong screen when configured to start in floating mode
[Originally reported by mark.kusch@…]
(2 screens, 0 and 1.

Setup MPlayer to start floating in ~/.i3/config:

```
$ ack -i mplayer .i3/config 
assign MPlayer → ~
```

Starting MPlayer from terminal on screen 1 results in the mplayer window gets mapped on screen 0.

From i3 logging:

```
08/03/2011 12:36:32 PM - WM_CLASS changed to xv (instance), MPlayer (class)
08/03/2011 12:36:32 PM - Using legacy window title. Note that in order to get Unicode window titles in i3, the application has to set _NET_WM_NAME (UTF-8)
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - match->dock = 2, window->dock = 0
08/03/2011 12:36:32 PM - dock status does not match
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - match->dock = 3, window->dock = 0
08/03/2011 12:36:32 PM - dock status does not match
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - match->dock = 2, window->dock = 0
08/03/2011 12:36:32 PM - dock status does not match
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - match->dock = 3, window->dock = 0
08/03/2011 12:36:32 PM - dock status does not match
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - window class does not match
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - window class matches (MPlayer)
08/03/2011 12:36:32 PM - COMMAND: *[id="23068673"] floating enable*
start
criteria: window id = 23068673
window id as int = 23068673
match specification finished, matching...
checking if con 0x11ec7d0 / root matches
checking if con 0x11f5130 / HDMI2 matches
checking if con 0x11f52a0 / topdock matches
checking if con 0x11f5470 / content matches
checking if con 0x11f5640 / bottomdock matches
checking if con 0x11f5870 / HDMI3 matches
checking if con 0x11f5aa0 / topdock matches
checking if con 0x11f5cd0 / content matches
checking if con 0x11f5f00 / bottomdock matches
checking if con 0x11f6150 / 1 matches
checking if con 0x11f8d10 / 9 matches
checking if con 0x11f4690 / #00FF00 matches
08/03/2011 12:36:32 PM - checking window 10485767 ((null))
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x11f8ea0 / #0000FF matches
08/03/2011 12:36:32 PM - checking window 10485770 ((null))
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1201730 / #ff00ff matches
08/03/2011 12:36:32 PM - checking window 14680184 (Firefox)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1201a50 / 2 matches
checking if con 0x1201c70 / #ffff00 matches
08/03/2011 12:36:32 PM - checking window 16777219 (Gajim.py)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1201ef0 / #aa0000 matches
08/03/2011 12:36:32 PM - checking window 20971550 (luakit)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1202880 / #00FF00 matches
08/03/2011 12:36:32 PM - checking window 16781935 (Gajim.py)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x12026e0 / #0000FF matches
checking if con 0x1212b70 / 8 matches
checking if con 0x1202b60 / #ffff00 matches
08/03/2011 12:36:32 PM - checking window 4194334 (URxvt)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1202de0 / #aa0000 matches
08/03/2011 12:36:32 PM - checking window 4194353 (URxvt)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1203280 / 7 matches
checking if con 0x1202f50 / #ff0000 matches
08/03/2011 12:36:32 PM - checking window 4194428 (URxvt)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x12036a0 / #00FF00 matches
08/03/2011 12:36:32 PM - checking window 4194447 (URxvt)
08/03/2011 12:36:32 PM - window id does not match
doesnt match
checking if con 0x1203ce0 / #0000FF matches
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - match made by window id (23068673)
matches window!
matching: 0x1203ce0 / #0000FF
match parsed
matching: 0x1203ce0 / #0000FF
should switch mode to tiling
08/03/2011 12:36:32 PM - workspace visible? fs = 0x1203280, ws = 0x1203280
single command completely parsed, dropping state...
done, json output = (null)
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - window class does not match
08/03/2011 12:36:32 PM - checking window 23068673 (MPlayer)
08/03/2011 12:36:32 PM - window class does not match
```

### LINKED ISSUE #1341: Inconsistency in window frame offsetting
[Originally reported by lolilolicon@…]
(I notice the window frame in i3 is handled inconsistently between the left frame and the top (title bar) frame. For example, in my case, the title bar is 20 pixels in height, so if I run `mpv --geometry +0+20 video.mkv`, the window frame is placed with its left-top corner at `(0, 0)`; this is because i3 automatically shifts the mpv window 2 pixels (the size of the left frame/border) to the right, but does not automatically shift the mpv window down in the same manner. This results in unexpectedly that `mpv --geometry +0+11` will make i3 put the mpv window at the center of the screen, presumably because i3 calculates that the left-top corner of the frame would be at `(0, -9)` and decides to resort to putting it at the center of the screen.

The discussion above ignores the fact that the win_gravity of the mpv window is actually `CenterGravity`, not `NorthWestGravity`, which I _think_ may change the expected resulting frame coordinates. (To be tested in Mutter when I get the chance).

### PR DESCRIPTION
**Pull request by orestisfl**
This needs some discussion.

In https://github.com/i3/i3/blob/a9512c6345ae66c658e215396be1278754471671/src/floating.c#L285-L304
we check if the floating container spawns in a different output (/workspace).
Why do we use relative coordinates? When a window opens in a different output, is the relative position valuable?

Later in `floating_enable` https://github.com/i3/i3/blob/a9512c6345ae66c658e215396be1278754471671/src/floating.c#L323-L327
we follow a different logic since we call `floating_maybe_reassign_ws()` which will reassign the new container to a different output.

Some history:
- commit f613df48d23e3f934129c79726d438ee19f2400c that fixes #297 adds the `floating_maybe_reassign_ws()` call in the end of `floating_enable`.
- commit 247e115835f6a4c1ee2eaee722f2ff6f46541e7b that fixes #452 adds the relative coordinates part.
- maybe related to #1335.
- related to #2661.

Fixes #1341.

### CODE REVIEW

**Comment by Airblader** [comment]
> Why do we use relative coordinates?

Doesn't `rect` contain absolute coordinates? That's how I remember it, anyway.

File: src/randr.c [hunk 1]
```diff
@@ -139,24 +153,34 @@ Output *get_output_with_dimensions(Rect rect) {
  * In contained_by_output, we check if any active output contains part of the container.
  * We do this by checking if the output rect is intersected by the Rect.
  * This is the 2-dimensional counterpart of get_output_containing.
- * Since we don't actually need the outputs intersected by the given Rect (There could
- * be many), we just return true or false for convenience.
+ * Returns the output with the maximum intersecting area.
  *
  */
-bool contained_by_output(Rect rect) {
+Output *contained_by_output(Rect rect) {
```
Comment (Airblader) [inline src/randr.c]: This method seems like a misnomer now.

File: src/floating.c [hunk 2]
```diff
@@ -320,21 +319,6 @@ void floating_enable(Con *con, bool automatic) {
     if (set_focus)
         con_activate(con);
 
-    /* Check if we need to re-assign it to a different workspace because of its
-     * coordinates and exit if that was done successfully. */
-    if (floating_maybe_reassign_ws(nc)) {
```
Comment (Airblader) [inline src/floating.c]: Don't we need this still?

File: src/randr.c (hunk 1 above)
Comment (Airblader) [reply src/randr.c]: Sounds good :-)

Comment (orestisf1993) [reply src/randr.c]: Up

**Review by Airblader — APPROVED** [review]

**Comment by LevitatingBusinessMan** [comment]
Wait, does this PR mean that if a window is placed at (0,0) the frame should be visible?

Like mentioned in https://github.com/i3/i3/issues/1341 which was marked closed with this?
If so I am still facing this "bug".
