### PR TITLE
Fix sticky-related crash (#3075)

### LINKED ISSUE #3075: sticky-related crash
This is should be the issue mentioned in #2973.

Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14-191-g9d2d602d (2017-12-09, branch "next") © 2009 Michael Stapelberg and contributors
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5640471028170752.bz2

**What I did:**

Start i3 with the following config:
```
# i3 config file (v4)

fake-outputs 800x500+0+0,800x500+800+0,800x500+800+500,800x500+0+500

mouse_warping none  # unrelated
focus_follows_mouse no  # unrelated

exec bash -c 'urxvt -e i3-msg sticky enable, floating enable, workspace 3, workspace 5'
```

**What I saw:**

i3 crashed

**What I expected instead:**

i3 should not have crashed

```
==18194==ERROR: AddressSanitizer: heap-use-after-free on address 0x6140000028a8 at pc 0x555928a29642 bp 0x7ffffa60be50 sp 0x7ffffa60be40
READ of size 8 at 0x6140000028a8 thread T0
    #0 0x555928a29641 in output_push_sticky_windows ../../i3/src/output.c:102
    #1 0x555928a62e8d in _workspace_show ../../i3/src/workspace.c:482
    #2 0x555928a62f48 in workspace_show_by_name ../../i3/src/workspace.c:500
    #3 0x55592897ac7e in cmd_workspace_name ../../i3/src/commands.c:970
    #4 0x55592899de70 in GENERATED_call parser/GENERATED_command_call.h:406
    #5 0x55592899fd52 in next_state ../../i3/src/commands_parser.c:185
    #6 0x5559289a1e6c in parse_command ../../i3/src/commands_parser.c:346
    #7 0x5559289f5c9b in handle_run_command ../../i3/src/ipc.c:124
    #8 0x555928a01636 in ipc_receive_message ../../i3/src/ipc.c:1245
    #9 0x7f0a0d1774e2 in ev_invoke_pending (/usr/lib/libev.so.4+0x44e2)
    #10 0x7f0a0d17aad5 in ev_run (/usr/lib/libev.so.4+0x7ad5)
    #11 0x555928a0c76f in ev_loop /usr/include/ev.h:835
    #12 0x555928a180b2 in main ../../i3/src/main.c:964
    #13 0x7f0a0bb4bf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
    #14 0x555928957749 in _start (/home/orestis/Documents/programming/i3/build/i3+0x186749)

0x6140000028a8 is located 104 bytes inside of 448-byte region [0x614000002840,0x614000002a00)
freed by thread T0 here:
    #0 0x7f0a100d4711 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:45
    #1 0x5559289a4b44 in con_free ../../i3/src/con.c:96
    #2 0x555928a534eb in tree_close_internal ../../i3/src/tree.c:333
    #3 0x555928a62c65 in _workspace_show ../../i3/src/workspace.c:453
    #4 0x555928a62f48 in workspace_show_by_name ../../i3/src/workspace.c:500
    #5 0x55592897ac7e in cmd_workspace_name ../../i3/src/commands.c:970
    #6 0x55592899de70 in GENERATED_call parser/GENERATED_command_call.h:406
    #7 0x55592899fd52 in next_state ../../i3/src/commands_parser.c:185
    #8 0x5559289a1e6c in parse_command ../../i3/src/commands_parser.c:346
    #9 0x5559289f5c9b in handle_run_command ../../i3/src/ipc.c:124
    #10 0x555928a01636 in ipc_receive_message ../../i3/src/ipc.c:1245
    #11 0x7f0a0d1774e2 in ev_invoke_pending (/usr/lib/libev.so.4+0x44e2)

previously allocated by thread T0 here:
    #0 0x7f0a100d4ce1 in __interceptor_calloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:70
    #1 0x555928a8ad0d in scalloc ../../i3/libi3/safewrappers.c:31
    #2 0x5559289a35f1 in con_new_skeleton ../../i3/src/con.c:40
    #3 0x5559289a3f8a in con_new ../../i3/src/con.c:71
    #4 0x555928a5fbb5 in create_workspace_on_output ../../i3/src/workspace.c:178
    #5 0x555928a2fa0f in init_ws_for_output ../../i3/src/randr.c:496
    #6 0x5559289d749f in fake_outputs_init ../../i3/src/fake_outputs.c:77
    #7 0x555928a14ece in main ../../i3/src/main.c:714
    #8 0x7f0a0bb4bf49 in __libc_start_main (/usr/lib/libc.so.6+0x20f49)
```

### PR DESCRIPTION
**Pull request by orestisf1993**
The first commit is unrelated, I can remove it. For an explanation of problem & solution check the second commit message.

Fixes #3075.

### CODE REVIEW

File: src/workspace.c [hunk 1]
```diff
@@ -451,13 +451,10 @@ static void _workspace_show(Con *workspace) {
...
             tree_close_internal(old, DONT_KILL_WINDOW, false, false);
+            ipc_send_workspace_event_from_gen(gen);
 
-            const unsigned char *payload;
-            ylength length;
-            y(get_buf, &payload, &length);
-            ipc_send_event("workspace", I3_IPC_EVENT_WORKSPACE, (const char *)payload);
-
-            y(free);
+            if (old == old_focus)
```
Comment (Airblader) [inline src/workspace.c]: Can you please add a short comment here that explains why this is done? And while you're at it, please use braces around the `if` as we try to have them consistently. :-)

**Comment by orestisf1993** [comment]
up
