### PR TITLE
Fix focus order in floating_disable & floating_enable for unfocused windows

### LINKED ISSUE #1975: Inconsistent focus fallback behavior
A user described [this incident](https://faq.i3wm.org/question/6767/automatically-move-focus-back-to-tiling-when-floating-window-is-closed/?comment=6777#comment-6777) on the FAQ page. I can reproduce that I think is taking place here as follows.

Set up containers 1 through 4 as shown in the picture below. Now focus, in this order, 3–1–4–2. If you now keep closing the terminals, the focus will jump to 4 and then to 3, the other floating container, and not 1, which a user may expect to happen.

Now set up the same situation again and focus in the same order, 3–1–4–2. Type `sleep 3 && exit` into terminal 2 and switch focus to terminal 4. Once 2 is closed, if you exit out of terminal 4, focus will jump to terminal 1 and not 3 as before, even though from the user point of view there's not much of a difference between the two situations.

screenshot-2015-10-02_21-30-49

i3 4.11

### LINKED ISSUE #2938: Enabling / disabling floating for containers from other workspace loses their focus
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14-8-g85eb0976 (2017-09-05, branch "makepkg") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.14-40-gbcaec964 (2017-09-11, branch "remotes/origin/HEAD") (pid 902)
Loaded i3 config: /tmp/i3.config (Last modified: Tue 12 Sep 2017 11:42:24 AM EEST, 27 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/orestis/Documents/programming/i3/build/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5751832013963264.bz2

**What I did:**
1. open 2 windows on workspace 1.
2. run `i3-msg floating enable && i3-msg mark A` for the second one. It is now focused & floating.
3. switch to workspace 2
4. run `i3-msg '[con_mark=A]' floating disable`
5. switch back to workspace 1

**What I saw:**
Window marked as A is not floating & is not focused.

**What I expected instead:**
Window marked as A is not floating & is still focused.

### PR DESCRIPTION
**Pull request by orestisf1993**
Fixes #2938 
Fixes #1975

### CODE REVIEW

**Comment by Airblader** [comment]
I don't expect test cases for this, but what happens in the following situations now?

* One floating window on another workspace, but it is not the focused one within the workspace. What has focus in that workspace after unfloating it?
* Two floating windows on another workspace and the focused one is unfloated
* Two floating windows on another workspace and the one not focused is unfloated

My expectation would be that

* the unfloated window will never be focused (on that workspace)
* the unfloated window is focused (on that workspace)
* the still floating window is focused (on that workspace)

**Comment by orestisf1993** [comment]
> I don't expect test cases for this

Why not? I was looking ideas for more testcases.

1. 👍 
2. 👍 
3. 👎 Will investigate. The exact configuration is: tiled, floating1 floating2 & focus stack: floating2 > floating1 > tiled. For focus stack: floating2 > tiled > floating1 we already have the expected behavior.

**Comment by Airblader** [comment]
By all means, feel free to add testcases. I just wanted to make clear that I'm only asking about the behavior. :-)

**Comment by orestisf1993** [comment]
The problem is that I wasn't checking for floating containers in my loop. Will push after I write the tests.

**Comment by orestisf1993** [comment]
Up! I actually fixed it by removing code.

**Comment by orestisf1993** [comment]
Squashed, added fix for `floating_enable()`. Probably looking for more test case ideas.

File: src/con.c [hunk 1]
```diff
@@ -1328,6 +1328,20 @@ orientation_t con_orientation(Con *con) {
...
 
 /*
+ * Returns the next container in the focus head of con's parent.
+ *
+ */
+Con *con_next_focused_tail(Con *con) {
+    Con *current;
+    TAILQ_FOREACH(current, &(con->parent->focus_head), focused) {
+        if (current == con) {
+            return TAILQ_NEXT(current, focused);
```
Comment (Airblader) [inline src/con.c]: Doesn't this mean this entire function is effectively the same as just `TAILQ_NEXT(con, focused)`?

File: include/con.h [hunk 2]
```diff
@@ -324,6 +324,12 @@ bool con_move_to_mark(Con *con, const char *mark);
 orientation_t con_orientation(Con *con);
 
 /**
+ * Returns the next container in the focus head of con's parent.
+ *
+ */
+Con *con_next_focused_tail(Con *con);
```
Comment (Airblader) [inline include/con.h]: What does the `tail` refer to in this function?

File: src/floating.c [hunk 3]
```diff
@@ -346,34 +359,43 @@ void floating_disable(Con *con, bool automatic) {
...
     Con *parent = con->parent;
 
+    Con *focus_tail_position = NULL;
+    Con *tiling_focused = con_descend_tiling_focused(ws);
+    /* No need to find focus order if focus is going to be set latter or if we are
+     * attaching to a workspace. */
+    if (!set_focus && tiling_focused->type != CT_WORKSPACE) {
+        focus_tail_position = con_next_focused_tail(parent);
+    }
+    DLOG("move_to_focus_head=%p\n", focus_tail_position);
```
Comment (Airblader) [inline src/floating.c]: This log statement is now lying. :-) Either way, instead of dumping the variable name it'd be more useful to log what we are going to do with this container.

File: src/floating.c [hunk 4]
```diff
@@ -346,34 +359,43 @@ void floating_disable(Con *con, bool automatic) {
     Con *ws = con_get_workspace(con);
     Con *parent = con->parent;
 
+    Con *focus_tail_position = NULL;
+    Con *tiling_focused = con_descend_tiling_focused(ws);
+    /* No need to find focus order if focus is going to be set latter or if we are
```
Comment (Airblader) [inline src/floating.c]: s/latter/later/

**Comment by orestisf1993** [comment]
Updated

**Comment by orestisf1993** [comment]
Still has problems. Don't merge. Will edit this comment.

**Comment by orestisf1993** [comment]
Updated. The new testcases crash my previous implementation.

**Comment by orestisf1993** [comment]
@Airblader please remove the `waiting` label.

**Comment by orestisf1993** [comment]
After https://github.com/i3/i3/pull/2969#issuecomment-330668431 I modified the code of `insert_con_into` to fix the problems of `move` I described and reused the function in `floating_disable`. It is in a very early stage and I can't clean it up right now but it might be a better alternative:  
https://github.com/orestisf1993/i3/tree/issue-2938-insert_into

I'll see if I can reuse it for `floating_enable` too.

**Comment by orestisf1993** [comment]
Just pushed a commit that also fixes #1975. Will write a test for this and I could move it on a separate PR after #2975.

**Comment by Airblader** [comment]
Sorry, I'm currently a little lost on as to what your status for the PR ist (?) :-)

**Comment by orestisf1993** [comment]
I'd like to use `insert_con_into` from #2975 instead of the current implementation.

**Comment by Airblader** [comment]
Fair enough, let's continue there first.

**Comment by orestisf1993** [comment]
I've incorporated `insert_con_into` into `floating_disable`. Will investigate if `floating_enable` can be tidied up too but I think the PR can be reviewed right now.

I'll also run this patch on my machine for a while since it's a pretty risky PR.

File: src/floating.c [hunk 5]
```diff
@@ -196,12 +221,22 @@ void floating_enable(Con *con, bool automatic) {
     /* We insert nc already, even though its rect is not yet calculated. This
      * is necessary because otherwise the workspace might be empty (and get
      * closed in tree_close_internal()) even though it’s not. */
-    if (set_focus) {
```
Comment (orestisf1993) [inline src/floating.c]: We actually didn't need this branch since we call `con_activate` if `set_focus`.

File: src/floating.c [hunk 6]
```diff
@@ -196,12 +221,22 @@ void floating_enable(Con *con, bool automatic) {
...
-        TAILQ_INSERT_TAIL(&(ws->floating_head), nc, floating_windows);
+    TAILQ_INSERT_HEAD(&(ws->floating_head), nc, floating_windows);
```
Comment (orestisf1993) [inline src/floating.c]: Placement in the `floating_windows` stack is not ideal here. Eg if the focus order is F1 > T1 > F2 and we make T1 a floating container it should be below F1 but above F2. But since focus order doesn't always follow the floating order (with `focus_follows_mouse`) it is not a huge deal IMO.

File: src/floating.c [hunk 7]
```diff
@@ -176,11 +176,36 @@ void floating_enable(Con *con, bool automatic) {
...
+         * [ ... S_{i-1} S_{i} S_{i+1} ... ]
+         * Where S_{x} is a container tree and the container 'con' that is beeing switched to
+         * floating belongs in S_{i}. The new floating container, 'nc', will have the
+         * workspace as its parent so it needs to be placed in this stack. If C was focused
+         * we just need to call con_focus(). Otherwise, nc must be placed before or after S_{i}.
+         * We should avoid using the S_{i} container for our operations since it might get
+         * killed if it has no other children. So, the two possible positions are after S_{i-1}
+         * or before S_{i+1}.
+         */
+        focus_before_parent = TAILQ_FIRST(&(con->parent->focus_head)) == con;
```
Comment (orestisf1993) [inline src/floating.c]: I'll have to recheck this since it appears to be wrong. `con` can be the focused child of its parent but not the focused descendant of its ancestor, `focus_head_placeholder`.

Could use `is_focused_descendant()`.

File: src/floating.c (hunk 6 above)
Comment (orestisf1993) [reply src/floating.c]: The failed tests are probably because I changed the default from `_TAIL` to `_HEAD`. If we are not following the "ideal" strategy I think non-focused newly floating windows should be placed below all other existing floating windows, especially since one of them could be the currently focused window.

**Comment by orestisf1993** [comment]
Up. This will need some time to be reviewed but we can slowly work on it.

**Comment by Airblader** [comment]
I have some vacation in a week and will try to take a look at this then.

**Comment by Airblader** [comment]
Can you resolve the conflicts? :-)

File: src/floating.c [hunk 8]
```diff
@@ -346,27 +385,59 @@ void floating_disable(Con *con, bool automatic) {
     Con *ws = con_get_workspace(con);
     Con *parent = con->parent;
 
+    bool modify_focus_head = !set_focus;
+    Con *prev_focus_head = NULL;
+    Con *new_parent = con_descend_tiling_focused(ws);
+    if (new_parent->type != CT_WORKSPACE)
```
[the remark this answers is not in the document]
Comment (orestisf1993) [reply src/floating.c]: Wait, what did you review here?

[the remark this answers is not in the document]
Comment (Airblader) [reply src/floating.c]: I'm confused. What? :-)

[the remark this answers is not in the document]
Comment (orestisf1993) [reply src/floating.c]: I can't find where you placed the comment here, it shows as outdated, and I can't grep the code shown above either.

[the remark this answers is not in the document]
Comment (Airblader) [reply src/floating.c]: I'm a ninja! :-) I can't find it either. It was not that important anyway, so let's just ignore it.
