### PR TITLE
Do not count '\' in comment as line continuation 

### LINKED ISSUE #2176: config: Comment lines can be continued with '\'
I noticed today that comment lines ending in the line-continuation character `\`, which precede a non-comment line, cause the non-comment line to be ignored.  Presumably because the line continuation is honored, and the next line is considered part of the comment.

For example, the following would spawn only one of the two terminal windows a user might expect, because the first one is probably parsed as being commented out:

```shell
# comment with a line continuation character at the end \
exec gnome-terminal

# comment without line continuation character at the end
exec gnome-terminal
```

Of course now that I know this, I can avoid it, but it's fairly obtuse to discover because in some cases like the above there are no errors -- the line just silently fails to execute.  In other cases (namely, if there's a data dependency on the skipped directive later in the config) there's an error, but it's removed from the location of the actual problem.

Ideally, the config parser should apply line continuations after comments have been ignored.

---

This is reproducible for me with i3 4.11 on Ubuntu 15.10 using the packages from sur5r's repository:
```
$ i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.11 (2015-09-30, branch "4.11") (pid 26498)
Loaded i3 config: /home/jpk/.config/i3/config (Last modified: Tue 26 Jan 2016 01:03:17 AM EST, 1492 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
$ apt-cache policy i3
i3:
  Installed: 4.11-1~~wily1
  Candidate: 4.11-1~~wily1
  Version table:
 *** 4.11-1~~wily1 0
        500 http://debian.sur5r.net/i3/ wily/universe amd64 Packages
        100 /var/lib/dpkg/status
     4.10.3-1build1 0
        500 http://us.archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages
```

Here's a [minimal config](https://gist.github.com/thatjpk/0e5481610bf1044630d4) that reproduces the behavior (just the default `i3-config-wizard` config with the quoted snippet above appended).  
 - Current behavior: The session starts with one terminal open.  
 - Expected behavior: The session starts with two terminals open.

### PR DESCRIPTION
**Pull request by jolange**
fixes #2176 

I'll squash this into a single commit once you approved the changes.

@thatjpk: FYI

### CODE REVIEW

File: src/config_parser.c [hunk 1]
```diff
@@ -847,8 +847,14 @@ bool parse_file(const char *f, bool use_nagbar) {
             ELOG("Your line continuation is too long, it exceeds %zd bytes\n", sizeof(buffer));
         }
         continuation = strstr(buffer, "\\\n");
-        if (continuation) {
-            continue;
+        if (continuation){
+            /* do not count '\' in a comment as continuation */
+            if (strchr(buffer,'#')) {
```
Comment (Airblader) [inline src/config_parser.c]: What if the # is inside of a string etc? I don't think this sufficiently checks for a comment

Comment (jolange) [inline src/config_parser.c]: You are right. Color specifications is another such case...
Any others one has to consider?

Comment (Airblader) [inline src/config_parser.c]: We shouldn't be wondering what cases we have to consider. Checking for a comment here should be exactly the same as where we actually identify comments, using the same code.

Comment (jolange) [inline src/config_parser.c]: Sure, sounds reasonable. But I did not yet figure out how to do that. As far as I understand, this is completely defined via `parser-specs/config.spec`. Any hint or suggestion how to make use of this in this case would be helping.

Comment (Airblader) [inline src/config_parser.c]: Yes, you're right. I forgot that it's handled in the parser already (I was on mobile and didn't check). Anyway, I think the pattern for comments should be `^\s*#`.

Comment (jolange) [inline src/config_parser.c]: This would only match whole comment lines, but not `some-sensible-command # comment`, right?

**Comment by jolange** [comment]
For now, just "comment-only" lines are not continued:
```
# the following line should be continued
exec "sleep\
 1"

# this line should not be continued \
client.focused          #ff4040 #ff0000 \
#1793D1 #2e9ef4   #ff0000

exec "sleep 2" # don't continue\
exec "sleep 3"
```
becomes:
```
# the following line should be continued
exec "sleep 1"

# this line should not be continued \
client.focused          #ff4040 #ff0000 #1793D1 #2e9ef4   #ff0000

exec "sleep 2" # don't continueexec "sleep 3"
```

I think this is not consistent, but I don't see a nice way of checking if a line contains a comment at this point yet.

**Comment by jolange** [comment]
Sorry for the long silence here, I didn't have the time to take a closer look at this until now. Unfortunately, after finally putting some thought into it, I still don't see a good way to make use of parser information to check if the current line contains a comment.

IMO the options are
- Only disallow continuation of comment-only lines, while allowing it for lines just ending with a comment. (As currently implemented in this PR) [inconsistent]
- Figure out all possible occurences of `#` not introducing a comment (strings, colors, ...). [not a nice solution]
- Stay with the current behaviour. [= unexpected behaviour]

Of these, I'd prefer the last one meanwhile... If you see another (good) option, please let me know.

**Comment by Airblader** [comment]
No, I don't really see a better option either.

**Comment by thatjpk** [comment]
Yeah, I see the problem.  The thing that prompted me to file the issue was I didn't expect the behavior -- but now that I know about it, I can avoid it.  So if the best compromise is to leave the current behavior as is, then perhaps a note and an example about it in the documentation would be helpful.

**Comment by Airblader** [comment]
Feel free to provide a pull request to add that hint. :-)

**Comment by stapelberg** [comment]
Issue #268 is relevant — we currently don’t support comments at the end of lines at all.

So, strictly speaking, only lines which begin with a `#` sign are considered comments. If comment signs at the end of a line work in some places, that is a happy coincidence.

I would be okay with only skipping continuations in comment-only lines. I think people run into this issue rarely enough that making that situation strictly better is good enough.

**Comment by jolange** [comment]
> we currently don’t support comments at the end of lines at all.

Ah, thanks, I was not aware of that! (Never tried it before, first when working on this issue)

In that case I totally agree. So consider the current state of this PR as my proposal.

File: src/config_parser.c [hunk 2]
```diff
@@ -848,7 +849,13 @@ bool parse_file(const char *f, bool use_nagbar) {
         }
         continuation = strstr(buffer, "\\\n");
         if (continuation) {
-            continue;
+            /* do not count '\' in a comment as continuation */
+            if (regex_matches(re_comment, buffer)) {
```
Comment (stapelberg) [inline src/config_parser.c]: While the regular expression that you’re using *should* be doing the same thing as the `sscanf` call below, I think it’d be cleaner to actually re-use the `sscanf` call, both from a duplication point of view and also because it avoids compiling a likely rarely-used regular expression every time the configuration file is read.

I think we could move the `sscanf` call further up, possibly like so (untested):

```c
/* sscanf implicitly strips whitespace. */
const bool comment = (sscanf(buffer, "%511s %511[^\n]", key, value) < 1 ||
                      key[0] == '#' || strlen(key) < 3)
continuation = strstr(buffer, "\\\n");
if (continuation) {
  if (!comment) {
    continue;
  }
  DLOG("line continuation in comment is ignored: \"%.*s\"\n", (int)strlen(buffer) - 1, buffer);
  continuation = NULL;
}

strncpy(buf + strlen(buf), buffer, strlen(buffer) + 1);

/* Skip comments and empty lines. */
if (comment) {
  continue;
}
```

Comment (jolange) [inline src/config_parser.c]: Yes, you have a point there. But I would only use `key[0] == '#'` for the comment bool. In particular this suggestion does not work for comments without spaces: `#comment\`

Please see my proposed variation of this.

File: src/config_parser.c [hunk 3]
```diff
@@ -847,23 +846,26 @@ bool parse_file(const char *f, bool use_nagbar) {
         if (buffer[strlen(buffer) - 1] != '\n' && !feof(fstr)) {
             ELOG("Your line continuation is too long, it exceeds %zd bytes\n", sizeof(buffer));
         }
+
+        /* sscanf implicitly strips whitespace. */
+        const bool skipLine = (sscanf(buffer, "%511s %511[^\n]", key, value) < 1 || strlen(key) < 3);
```
Comment (stapelberg) [inline src/config_parser.c]: nit: for consistency, can you rename `skipLine` to `skip_line` please?

File: src/config_parser.c [hunk 4]
```diff
@@ -847,23 +846,26 @@ bool parse_file(const char *f, bool use_nagbar) {
...
+        const bool comment = key[0] == '#';
```
Comment (stapelberg) [inline src/config_parser.c]: nit: for consistency, can you please add parens, i.e. `const bool comment = (key[0] == '#');`?

**Comment by stapelberg** [comment]
Looks good overall, will merge once the nits are addressed.

**Comment by jolange** [comment]
@stapelberg done & rebased
