### PR TITLE
Make sure that parse_config input terminates with '\0'

### LINKED ISSUE #2934: Config file without newline at the end crashes i3
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14-8-g85eb0976 (2017-09-05, branch "makepkg") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.14-40-gbcaec964 (2017-09-11, branch "remotes/origin/HEAD") (pid 902)
Loaded i3 config: /tmp/i3.config (Last modified: Tue 12 Sep 2017 11:42:24 AM EEST, 27 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/orestis/Documents/programming/i3/build/i3
```

URL to a logfile as per http://i3wm.org/docs/debugging.html:
http://logs.i3wm.org/logs/5765033938124800.bz2
```
==13182==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61a00000053f at pc 0x7fc36761e01e bp 0x7ffe0e022ec0 sp 0x7ffe0e022668
READ of size 36 at 0x61a00000053f thread T0
    #0 0x7fc36761e01d in __interceptor_strchr /build/gcc-multilib/src/gcc/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:466
    #1 0x55fd5dceac51 in parse_config ../../i3/src/config_parser.c:265
    #2 0x55fd5dcf1a50 in parse_file ../../i3/src/config_parser.c:1090
    #3 0x55fd5dcd95d2 in parse_configuration ../../i3/src/config.c:65
    #4 0x55fd5dcddddf in load_configuration ../../i3/src/config.c:230
    #5 0x55fd5dd33649 in main ../../i3/src/main.c:543
    #6 0x7fc36315b4c9 in __libc_start_main (/usr/lib/libc.so.6+0x204c9)
    #7 0x55fd5dc79149 in _start (/home/orestis/Documents/programming/i3/build/i3+0x185149)

0x61a00000053f is located 0 bytes to the right of 1215-byte region [0x61a000000080,0x61a00000053f)
allocated by thread T0 here:
    #0 0x7fc3676a1860 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x55fd5dda9fb8 in smalloc ../../i3/libi3/safewrappers.c:24
    #2 0x55fd5dcf0fb2 in parse_file ../../i3/src/config_parser.c:1028
    #3 0x55fd5dcd95d2 in parse_configuration ../../i3/src/config.c:65
    #4 0x55fd5dcddddf in load_configuration ../../i3/src/config.c:230
    #5 0x55fd5dd33649 in main ../../i3/src/main.c:543
    #6 0x7fc36315b4c9 in __libc_start_main (/usr/lib/libc.so.6+0x204c9)
```

**What I did:**
Use the following config file: https://www.dropbox.com/s/vkxvsh3osfznq0z/config.zip?dl=0, start i3.
The content should not matter that much but I think a lot of lines are needed to make the problem appear.

**What I saw:**
i3 crashed.

### PR DESCRIPTION
**Pull request by orestisf1993**
Fixes #2934

### CODE REVIEW

File: src/config_parser.c [hunk 1]
```diff
@@ -1025,7 +1025,9 @@ bool parse_file(const char *f, bool use_nagbar) {
     /* Then, allocate a new buffer and copy the file over to the new one,
      * but replace occurrences of our variables */
     char *walk = buf, *destwalk;
-    char *new = smalloc(stbuf.st_size + extra_bytes + 1);
```
Comment (stapelberg) [inline src/config_parser.c]: A slightly simpler fix is to replace the `smalloc` call with an `scalloc` call.

Comment (orestisf1993) [reply src/config_parser.c]: Sure. A testcase only for the original issue?

Do you prefer the scalloc way?

Comment (stapelberg) [reply src/config_parser.c]: > A testcase only for the original issue?

I’m not sure how to parse the “only” in your sentence — yes, the testcase should exercise the code path which makes i3 crash currently, so that we don’t introduce this issue again. What else could it possibly test in the scope of this PR? :)

> Do you prefer the scalloc way?

I think so. We use it elsewhere for the same effect, so that’d be more consistent.

Comment (orestisf1993) [reply src/config_parser.c]: Ok will push the changes soon. You are right about the testcase, ignore my comment :)

Comment (orestisf1993) [reply src/config_parser.c]: Hmm, `launch_with_config` seems to add a newline when saving the config and config-parser tests don't cover the code that needs to be fixed.

Comment (stapelberg) [reply src/config_parser.c]: I think the best choice is to refactor `launch_with_config` to no longer add a newline, and add that newline in any tests where it is missing, if any.

**Comment by orestisf1993** [comment]
Test added

File: testcases/t/270-config-no-newline-end.t [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+# • http://onyxneon.com/books/modern_perl/modern_perl_a4.pdf
+#   (unless you are already familiar with Perl)
+#
+# Make sure that configs that end without a newline don't crash i3.
+# Ticket: #2934
+use i3test i3_autostart => 0;
+
+my $first_lines = <<'EOT';
+set $workspace1 workspace number 1
+set $workspace2 workspace number 2
```
Comment (stapelberg) [inline testcases/t/270-config-no-newline-end.t]: Please remove line 23 to 30, as they don’t affect the testcase’s outcome.

File: testcases/t/270-config-no-newline-end.t [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+set $workspace4 workspace number 4
+set $workspace5 workspace number 5
+set $workspace6 workspace number 6
+set $workspace7 workspace number 7
+set $workspace8 workspace number 8
+set $workspace9 workspace number 9
+set $workspace0 workspace eggs
+
+bindsym Mod4+1 $workspace1
+bindsym Mod4+2 $workspace2
```
Comment (stapelberg) [inline testcases/t/270-config-no-newline-end.t]: Please remove line 34 to 41

File: testcases/t/270-config-no-newline-end.t [hunk 4]
```diff
@@ -0,0 +1,56 @@
...
+bindsym Mod4+3 $workspace3
+bindsym Mod4+4 $workspace4
+bindsym Mod4+5 $workspace5
+bindsym Mod4+6 $workspace6
+bindsym Mod4+7 $workspace7
+bindsym Mod4+8 $workspace8
+bindsym Mod4+9 $workspace9
+EOT
+
+my $last_line = 'bindsym Mod4+0 $workspace0';
```
Comment (stapelberg) [inline testcases/t/270-config-no-newline-end.t]: Add a comment pointing out that the trailing newline is intentionally missing here.

File: testcases/t/270-config-no-newline-end.t [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+my $config = "${first_lines}${last_line}";
+
+my $pid = launch_with_config($config);
+sync_with_i3;
```
Comment (stapelberg) [inline testcases/t/270-config-no-newline-end.t]: The `sync_with_i3` call here shouldn’t be necessary, as you don’t change any X11 state in your testcase. Please remove or add a comment stating why it’s needed.

File: testcases/t/270-config-no-newline-end.t (hunk 3 above)
Comment (orestisf1993) [reply testcases/t/270-config-no-newline-end.t]: Thanks. I had tried removing some blocks before to minimize the buggy config but couldn't get it to crash.

**Comment by stapelberg** [comment]
Thank you!
