### PR TITLE
smart_borders: Deprecate option

### LINKED ISSUE #5406: "smart_borders no_gaps" option is broken
<pre>
[x] Bug
</pre>

### PR DESCRIPTION
**Pull request by orestisfl**
This had pretty much identical behaviour to hide_edge_borders which made it confusing. The `hide_edge_borders smart_no_gaps` implementation has an extra check which fixes #5406.

### CODE REVIEW

File: docs/userguide [hunk 1]
```diff
@@ -782,6 +782,7 @@ You can hide container borders adjacent to the screen edges using
 +hide_edge_borders+ (the default is +none+). Hiding borders is useful if you are
 using scrollbars, or do not want to waste even two pixels in displayspace.
 
+[[_smart_borders]]
```
Comment (stapelberg) [inline docs/userguide]: Could you mention smart_borders in the Syntax or Example with a comment stating that it’s an old syntax for “hide_edge_borders smart”? I’d like to make sure that people can Ctrl+f this page for every line of their config file and find details on it.

File: src/config_directives.c [hunk 2]
```diff
@@ -326,10 +326,12 @@ CFGFUN(gaps, const char *workspace, const char *scope, const long value) {
 }
 
 CFGFUN(smart_borders, const char *enable) {
+    ELOG("smart_borders is deprecated. Please use hide_edge_borders instead.\n");
```
Comment (stapelberg) [inline src/config_directives.c]: Why raise an error? We could just remove this line and translate smart_borders into hide_edge_borders == smart indefinitely. I don’t think it’s necessary to bother users to update their config file for this.

**Review by stapelberg — CHANGES_REQUESTED** [review]

File: src/config_directives.c (hunk 2 above)
Comment (orestisfl) [reply src/config_directives.c]: Moved the warning only when there is a conflict.

File: docs/userguide (hunk 1 above)
Comment (orestisfl) [reply docs/userguide]: I feel if we mention the old syntax as an example it's going to lead to people copying it. Added a simple mention of it.

**Review by stapelberg — APPROVED** [review]
