### PR TITLE
 Kill misbehaving subscribed clients instead of hanging

### LINKED ISSUE #2539: Seemingly random i3 freezes (SIGSTOP)
Arch Linux, 4.12-158-ge48119a

Since September (I think), `i3` randomly freezes.
Sending `SIGCONT` to i3 makes it responsive.
It seems I'm not the only one: https://marc.ttias.be/arch-general/2016-09/msg00067.php

*I'll try to get more info...*

### LINKED ISSUE #2999: enhancement: kill misbehaving IPC connections instead of deadlocking
Currently, i3 blockingly writes replies and events (only after subscribing, of course) to IPC clients. If an IPC client does not read from the connection for whichever reason, this will result in i3 blocking indefinitely, effectively freezing as far as users are concerned. (Side note: the same is true for reading, i.e. once i3 starts reading anything, it blockingly waits for the entire message to arrive. This turns out to not be a problem in practice.)

This is a recurring problem (see #2280 and #2539 for examples), so I’m filing this issue to brainstorm about what we could do about it, if anything.

My current favorite mitigation technique is to check whether the IPC connection’s file descriptor is writeable before sending a message (using `select(2)` with a 0 timeout). If not, we kill the connection, preventing a deadlock.

Here are a few more thoughts about this idea:

* We should spawn an i3-nagbar instance to inform users that they just ran into a third-party bug. Otherwise, software might start to rely on this behavior (e.g. it might not clean up IPC connections which are no longer used).
  * We should refer users to a help document on https://i3wm.org/docs where we explain how to further diagnose the issue.
* I considered using a timeout instead, but timeouts are very brittle: they make assumptions about how quickly processes run at *every point in time* on *vastly different computers*. E.g., if we decided to use a 10 second timeout, and another program starts swapping to hard disk (hence starving other processes for a while), i3 would incorrectly kill correctly functioning IPC clients. If we opt for a timeout that is too high, the mitigation becomes ineffective and users would still think that i3 hangs.
  * I think that the check-writeability approach will gracefully degrade on systems which are under high load: if the IPC client is slow, i3 will likely be slowed down to a somewhat similar extent.
* Linux-specific: as per http://elixir.free-electrons.com/linux/v4.13.4/source/include/net/sock.h#L2139 and https://stackoverflow.com/a/22007520/712014, UNIX sockets are reported as writeable as long as half of their send buffer is available. Linux’s default value for the default and maximum send buffer size is 212992 bytes, i.e. individual i3 messages must not exceed 106496 bytes for this mitigation technique to be effective. The largest messages we send are TREE replies, which can easily reach 60 kb in size (observed on my somewhat big session right now). Luckily, the most common case for deadlocks are events, which are significantly smaller in size, so we should be good.
  * We could use the (platform-specific) [`SIOCOUTQ` ioctl](https://manpages.debian.org/stretch/manpages/tcp.7.en.html#Ioctls) to get the number of unsent bytes, which — in combination with the send buffer size — would allow us to verify that the message we are about to send is going to fit. https://codesearch.debian.net/search?q=ioctl.*SIOCOUTQ%2C&perpkg=1 shows that a handful of programs use this ioctl.
* Some platforms have significantly lower send buffer size limits (IIRC, BSDs default to 32k), so i3 should try to increase the limit to the maximum value or 256k, whichever is lower.
* If the platform does not correctly report writeability, lacks the `SIOCOUTQ` (or similar) ioctl, or has a too strict limit on the maximum send buffer size, we’d fall back to the current behavior and deadlock.

Disclaimer: I have not actually implemented anything yet, so I’m not sure if this works out in practice.

cc @Airblader 
cc @acrisci 
cc @Merovius (we briefly spoke about this a few weeks ago)
cc @hannes to keep me honest about linux networking

### LINKED ISSUE #3084: i3 froze and crashed
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 1568)abort…)
Loaded i3 config: /home/thomas/.i3/config (Last modified: Tue 12 Dec 2017 11:34:18 CET, 4373 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

```

**What I did:**

Nothing.

i3 asked me to make a backtrace so I did.
[i3-backtrace.1568.0.txt](https://github.com/i3/i3/files/1551434/i3-backtrace.1568.0.txt)

**What I saw:**

i3 froze

**What I expected instead:**

i3 not to freeze

### PR DESCRIPTION
**Pull request by orestisf1993**
This change only affects clients that are subscribed to events, which should be the main cause of our problems.

In the common case (socket is immediately writeable) the behaviour doesn't change at all: the message is sent directly, no ev_io / ev_timeout callback is enabled. When a socket is found to be not writeable, instead of calling the blocking `ipc_send_message` we put the message in the tail of a queue and init a `ev_io` callback and a corresponding timer. If timer is triggered first, the socket is closed and the client connection is removed. If the socket becomes writeable before the timeout we either reset the timer if we couldn't push all stored messages or completely remove it if everything was pushed.

~~A simpler alternative is to immediately remove clients with non-writeable sockets (using the same `socket_writeable()` function):
https://github.com/orestisf1993/i3/tree/misbehaving-ipc-2999~~
The benefit of the queue + libev method is that we can allow timeouts that are orders of magnitude larger without blocking i3 temporarily.
Also, after reading through https://github.com/jaagr/polybar/issues/435: the approach here can help prevent deadlocks without killing an IPC connection (even though it relies on a timer but still).

We can still theoretically hang if the client stops reading while `ipc_send_message()` is writing the message. This is not a huge problem in practice but we could avoid it by using a simple non-blocking `write()` loop instead of `writeall()`. On `EAGAIN` we can return the amount of bytes written and save it in the `pending_message_t` struct. Then, when the socket is writeable again, we can continue writing from where we stopped.

We could also replace `ipc_send_message()` for all client connections in i3, not just those subscribed to events.

We can also limit the amount of messages stored and increase the timeout (or use multiple timeouts): eg it's ok if a client is not reading for 10 seconds and we are only holding 5KB of messages for them but it is not ok if they are inactive for 5 seconds and we have 30MB of messages held.

Closes #2999
Closes #2539

Low-info issue that should be re-reproduced:
Closes #3084 (OP uses an IPC script)

### CODE REVIEW

**Comment by orestisf1993** [comment]
We could also have an array instead of a TAILQ: https://github.com/i3/i3/pull/3263/commits/4902769560833ca7412097aed018b982028c4d09. Not very useful right now so I am squashing it away.

File: src/ipc.c [hunk 1]
```diff
@@ -1282,6 +1359,44 @@ static void ipc_receive_message(EV_P_ struct ev_io *w, int revents) {
...
+    /* If this callback is called then there should be a corresponding active
+     * timer. Would have caused a segfault anyway so an assertion here is ok. */
+    assert(client->timeout != NULL);
+
+    const ipc_push_result result = ipc_push_pending(client);
+    if (result == PUSHED_NONE) {
+        /* This should never happen but I am not brave enough to put an
+         * assertion here. Just clean everything to get out of this ugly
+         * situation. */
+        ELOG("libev reported socket as writeable but we couldn't push any message to ipc client with fd %d\n", w->fd);
```
Comment (orestisf1993) [inline src/ipc.c]: Ugh, I don't know what's wrong here, I found that this can happen `socket_is_writeable()` returns false even though libev reports the socket as writeable and `ipc_send_message()` succeeds. I found this case while investigating https://github.com/jaagr/polybar/issues/435 with a big loop: `for i in $(seq 1 15000); do i3-msg "workspace back_and_forth" &>/dev/null ; done`. Is my call to `select` wrong?

I think I should get rid of `socket_is_writeable` and write a non-blocking `write_all` / `ipc_send_message` that returns on `EAGAIN`.

**Comment by Airblader** [comment]
@orestisf1993 I'm sorry this sort of went totally by me. Is this ready to be reviewed from your point of view?

**Comment by orestisf1993** [comment]
Yes!

File: include/libi3.h [hunk 2]
```diff
@@ -166,6 +166,9 @@ int sasprintf(char **strp, const char *fmt, ...);
  */
 ssize_t writeall(int fd, const void *buf, size_t count);
 
+//TODO
```
Comment (Airblader) [inline include/libi3.h]: TODO :)

File: src/ipc.c [hunk 3]
```diff
@@ -38,6 +38,138 @@ static void set_nonblock(int sockfd) {
         err(-1, "Could not set O_NONBLOCK");
 }
 
+//TODO
```
Comment (Airblader) [inline src/ipc.c]: TODO :)

File: src/ipc.c [hunk 4]
```diff
@@ -38,6 +38,138 @@ static void set_nonblock(int sockfd) {
...
+}
+
+typedef enum {
+    WRITE_ERROR,
+    WRITE_NONE,
+    WRITE_PARTIAL,
+    WRITE_ALL,
+} write_result_t;
+
+//TODO
```
Comment (Airblader) [inline src/ipc.c]: TODO :)

**Comment by orestisf1993** [comment]
Thanks, forgot about them. They are about the docstrings for each respective function, I wanted to reach a decision about the structure of the code first, I wasn't sure you are going to like the changes in libi3.

**Comment by Airblader** [comment]
Yeah, the changes are why I requested a review from @stapelberg as well.

**Comment by stapelberg** [comment]
Sorry for the long wait.

> A simpler alternative is to immediately remove clients with non-writeable sockets (using the same socket_writeable() function):
> https://github.com/orestisf1993/i3/tree/misbehaving-ipc-2999
> The benefit of the queue + libev method is that we can allow timeouts that are orders of magnitude larger without blocking i3 temporarily.

I think I’d prefer trying the simple approach first (immediately killing clients where writes block): 

Socket buffers are typically large enough to not block during normal operation (except perhaps on OpenBSD, which, AFAIR, is more conservative). To be sure, we could try increasing the buffer size programmatically for the sockets we’re using.

If this turns out not to work, we can revisit the queueing approach.

Does that make sense?

**Comment by orestisf1993** [comment]
The benefits of the queue outweight the small extra complexity IMO. i3 won't block its operation and we will avoid possible deadlocks like the issue in polybar. We will also have to decide how we are going to solve the timer problem you mentioned:

> I considered using a timeout instead, but timeouts are very brittle: they make assumptions about how quickly processes run at every point in time on vastly different computers. E.g., if we decided to use a 10 second timeout, and another program starts swapping to hard disk (hence starving other processes for a while), i3 would incorrectly kill correctly functioning IPC clients. If we opt for a timeout that is too high, the mitigation becomes ineffective and users would still think that i3 hangs.
>
> I think that the check-writeability approach will gracefully degrade on systems which are under high load: if the IPC client is slow, i3 will likely be slowed down to a somewhat similar extent.

**Comment by stapelberg** [comment]
> i3 won't block its operation

…but with the simple approach, we would never block either? What am I missing here?

**Comment by orestisf1993** [comment]
If we don't block at all, we might kill a client that is still functional,
as you mentioned in the issue.

**Comment by stapelberg** [comment]
In the issue, I also mention:

> I think that the check-writeability approach will gracefully degrade on systems which are under high load: if the IPC client is slow, i3 will likely be slowed down to a somewhat similar extent.

So, my current best guess is still that a writability check should work, and we should only consider more complicated solutions if it doesn’t work well in practice.

**Comment by orestisf1993** [comment]
But we might introduce a problem that might be hard to spot & reproduce, it
might mean IPC client developers trying to fix things by restarting the
connection from their end (which will lead to data loss).

Clients slower than i3 will always die when there is heavy activity since
reaching the data limit will make the socket not writeable.

Closing a connection on EAGAIN just doesn't sound like a good idea to me.

**Comment by stapelberg** [comment]
> But we might introduce a problem that might be hard to spot & reproduce, it
> might mean IPC client developers trying to fix things by restarting the
> connection from their end (which will lead to data loss).

We could make the code pop up a nagbar with an appropriate message, and revert it early on if it indeed causes issues.

> Clients slower than i3 will always die when there is heavy activity since
> reaching the data limit will make the socket not writeable.

Yeah, but I don’t see why clients would be drastically slower than i3, and the limit should be sufficiently high that this seems unlikely.

> Closing a connection on EAGAIN just doesn't sound like a good idea to me.

Well, it does seem like a good idea to me, or at least one that’s worthwhile trying. At this point, with two opposing opinions, I think we’ll just have to gather some data to clearly say whether it works or whether it doesn’t :).

**Comment by orestisf1993** [comment]
I have a real life example. I wrote this quick script to use with [thyme](https://github.com/sourcegraph/thyme):

```python
#!/usr/bin/env python3
import os
import i3ipc

i3 = i3ipc.Connection()

def on_window(*_):
    os.system('thyme track -o thyme.json')


i3.on('window::focus', on_window)

try:
    i3.main()
finally:
    i3.quit()
```

The thyme call should be around 8ms max, which isn't much since a simple "hello world" in python takes 5ms on my system.

Now, if I create 5-6 windows in a tabbed container and scroll through them back and forth using the scroll wheel, I'll eventually reach a point where `EAGAIN` is returned in `writeall`. This problem will certainly be amplified in more conservative systems.

Another possible example of a slower client is polybar.

> Well, it does seem like a good idea to me

I partially don't like it because it doesn't seem to be a good practice. We are responding destructively to an error called "Resource unavailable, try again"

**Comment by stapelberg** [comment]
> Now, if I create 5-6 windows in a tabbed container and scroll through them back and forth using the scroll wheel, I'll eventually reach a point where EAGAIN is returned in writeall. This problem will certainly be amplified in more conservative systems.

Thanks for the example. It’s always helpful to talk about specific code.

In this case, I’d argue that the architecture of the program should be improved: you have a high-volume event stream (focus events) coming in, and a low-volume processing capability (os.system calls). You must make a policy decision here: do you want to queue events, or is it preferable to discard events and catch up eventually?

I think we shouldn’t dictate the policy by always queueing, but rather authors should decide what makes the most sense for the program they’re writing.

> I partially don't like it because it doesn't seem to be a good practice. We are responding destructively to an error called "Resource unavailable, try again"

The fact that we’re getting `EAGAIN` does not imply that the only response is to retry, otherwise the kernel could just retry on our behalf, and we could remove `EAGAIN` :). Rather, we’re given the option to retry, and I’d argue that in this case, it’d be better not to retry.

**Comment by stapelberg** [comment]
Side note: it would be interesting to figure out how X11 reacts to hanging clients.

**Comment by orestisf1993** [comment]
With the queue implementation from i3's side authors can just follow the intuitive approach when writing their applications, without caring for edge cases, high load etc. Since we frequently ask users to implement their own feature request using the IPC interface, many of them are not necessarily experienced programmers and won't like the extra work that they'll have to put into their script.
It is an "environmentally friendly" solution too, since the queue code will need to be written only from i3's side once, instead of being implemented on all ipc clients.

>I think we shouldn’t dictate the policy by always queueing, but rather authors should decide what makes the most sense for the program they’re writing.

We aren't dictating anything, we just make the queue policy easier to implement:

| | queue | kill clients |
|------------- | ------------- | ------------- |
| client wants: **queue policy** | Handled by i3 | Needs to be implemented by the client, client killed if not fast enough |
| client wants: **discard policy** | Needs to be implemented by the client, events queued by i3 if not fast enough | Needs to be implemented by the client, client killed if not fast enough |

> Side note: it would be interesting to figure out how X11 reacts to hanging clients.

xserver seems to queue data until they can't allocate any more memory:
https://github.com/mirror/xserver/blob/1c7f34e99ff9750979a03ae20c6be1f2b42c284c/os/io.c#L809-L817
`ETEST` here is a macro that essentially checks for `EAGAIN`:
https://github.com/mirror/xserver/blob/1c7f34e99ff9750979a03ae20c6be1f2b42c284c/os/io.c#L887

Maybe they have a less passive approach somewhere for clients that stop reading for too long.

**Comment by orestisf1993** [comment]
1. Yes, this approach is simpler. I've made the changes, seems to work but might need some polishing.

File: libi3/safewrappers.c [hunk 5]
```diff
@@ -66,23 +66,36 @@ int sasprintf(char **strp, const char *fmt, ...) {
     return result;
 }
 
-ssize_t writeall(int fd, const void *buf, size_t count) {
-    size_t written = 0;
-    ssize_t n = 0;
-
+static ssize_t _writeall(int fd, const void *buf, size_t count, bool block, size_t written) {
```
Comment (orestisf1993) [inline libi3/safewrappers.c]: I feel that you won't like this. Would you rather have each function separate? (`writeall_nonblock` will moved to ipc.c).

File: src/ipc.c [hunk 6]
```diff
@@ -38,6 +38,88 @@ static void set_nonblock(int sockfd) {
...
+            FREE(client->timeout);
+        }
+        ev_io_stop(main_loop, client->callback);
+        return;
+    }
+
+    ev_io_start(main_loop, client->callback);
+    if (!client->timeout) {
+        struct ev_timer *timeout = scalloc(1, sizeof(struct ev_timer));
+        ev_timer_init(timeout, ipc_client_timeout, 10.0, 0.);
```
Comment (stapelberg) [inline src/ipc.c]: Does the delay of 10s imply that there could be user-visible hangs for up to 10 seconds? If so, that seems excessive. How about 1s instead?

File: src/ipc.c [hunk 7]
```diff
@@ -1285,6 +1362,25 @@ static void ipc_receive_message(EV_P_ struct ev_io *w, int revents) {
     FREE(message);
 }
 
+static void ipc_client_timeout(EV_P_ ev_timer *w, int revents) {
+    /* No need to be polite and check for writeability, the other callback would
+     * have been called by now. */
+    ipc_client *client = (ipc_client *)w->data;
+
+    LOG("client %p on fd %d timed out, killing\n", client, client->fd);
```
Comment (stapelberg) [inline src/ipc.c]: We’ll need an ELOG here instead of a LOG. We should try to get the cmdline of the remote process and include it in the error message.

File: src/ipc.c (hunk 6 above)
Comment (orestisf1993) [reply src/ipc.c]: The delay is done asynchronously. New messages are appending at the end of the buffer while i3 continues its normal operation.

File: src/ipc.c (hunk 7 above)
Comment (orestisf1993) [reply src/ipc.c]: Is it possible to get the process id / cmdline using the socket?

File: src/ipc.c (hunk 6 above)
Comment (stapelberg) [reply src/ipc.c]: Even if new messages are appended, can there ever be a 10s delay?

File: src/ipc.c (hunk 7 above)
Comment (stapelberg) [reply src/ipc.c]: Yes. You can use the SO_PEERCRED socket option to find the pid of the remote end of a UNIX socket, then read its `/proc/<pid>/cmdline`.

File: src/ipc.c (hunk 6 above)
Comment (orestisf1993) [reply src/ipc.c]: Delay on which side? i3 will not see any delay.

File: libi3/safewrappers.c (hunk 5 above)
Comment (orestisf1993) [reply libi3/safewrappers.c]: Moving it to ipc.c fails a travis test. Keep it in safewrappers.c as a separate function?

Comment (stapelberg) [reply libi3/safewrappers.c]: Or update the travis test? :)

Comment (orestisf1993) [reply libi3/safewrappers.c]: That would require to exclude the whole ipc.c from check-safe-wrappers.sh

Comment (stapelberg) [reply libi3/safewrappers.c]: Let’s leave the function in safewrappers.c, then.

File: src/ipc.c [hunk 8]
```diff
@@ -1285,6 +1374,67 @@ static void ipc_receive_message(EV_P_ struct ev_io *w, int revents) {
...
+        if (c == '\0') {
+            space = true;
+        } else {
+            cmdline[len++] = c;
+            space = false;
+        }
+    }
+    cmdline[len] = '\0';
+    free(exepath);
+    fclose(f);
```
Comment (stapelberg) [inline src/ipc.c]: I think the algorithm can be more clearly expressed (and without as many memory allocations) by first reading, then replacing. The old `open` call allows working with the number of bytes that were read, which seems harder with `fopen`. How about this:

```c
  char *cmdline = NULL;
  int fd = open(exepath, O_RDONLY);
  free(exepath);
  if (fd == -1) {
    goto end;
  }
  
  char buf[512] = {'\0'}; // cut off cmdline for the error message
  const ssize_t n = read(fd, buf, sizeof(buf));
  close(fd);    
  if (n < 0) {
    goto end;
  }
  for (char *walk = buf; walk < buf+n-1; walk++) {
    if (*walk == '\0') {
      *walk = ' ';
    }
  }
  cmdline = buf;
```

File: src/ipc.c [hunk 9]
```diff
@@ -38,6 +38,100 @@ static void set_nonblock(int sockfd) {
...
+        ev_io_stop(main_loop, client->callback);
+        return;
+    }
+
+    /* Otherwise, make sure that the io callback is enabled and create a new
+     * timer if needed. */
+    ev_io_start(main_loop, client->callback);
+    if (!client->timeout) {
+        struct ev_timer *timeout = scalloc(1, sizeof(struct ev_timer));
+        ev_timer_init(timeout, ipc_client_timeout, 10.0, 0.);
```
Comment (stapelberg) [inline src/ipc.c]: Here and below, IIUC, the 10.0 is the timeout after which we kill the client connection, yes? Can you introduce a constant for it? E.g. `const ev_tstamp kill_timeout = 10.0;`

File: libi3/safewrappers.c [hunk 10]
```diff
@@ -83,6 +83,22 @@ ssize_t writeall(int fd, const void *buf, size_t count) {
     return written;
 }
 
+ssize_t writeall_nonblock(int fd, const void *buf, size_t count) {
+    size_t written = 0;
+    while (written < count) {
+        ssize_t n = write(fd, buf + written, count - written);
+        if (n == -1) {
+            if (errno == EAGAIN || errno == EINTR) {
```
[the remark this answers is not in the document]
Comment (orestisf1993) [reply libi3/safewrappers.c]: Yes. How do you think we should handle it in this function? Retrying on EINTR, like in `writeall`, should be fine.

[the remark this answers is not in the document]
Comment (stapelberg) [reply libi3/safewrappers.c]: Yes, retrying sounds like the correct thing to do.

**Comment by orestisf1993** [comment]
up

File: include/libi3.h [hunk 11]
```diff
@@ -166,6 +166,13 @@ int sasprintf(char **strp, const char *fmt, ...);
  */
 ssize_t writeall(int fd, const void *buf, size_t count);
 
+/**
+ * Like writeall but instead of repeating the write on EAGAIN / EINTR, the
```
Comment (stapelberg) [inline include/libi3.h]: The first line is no longer accurate. Also, strictly speaking, it should be “number of bytes”, because they’re countable :). How about this:

“Like writeall, but instead of retrying upon EINTR (returned when a write would block), the function stops and returns the total number of bytes written so far.”

**Comment by stapelberg** [comment]
Well, a testcase which opens an IPC connection, subscribes to events, no longer reads from the connection, triggers enough events to ensure writes will block, and finally verifies that a new connection will work just fine (i.e. i3 doesn’t hang), but the existing connection was closed.

Does that make sense?

**Comment by orestisf1993** [comment]
Ok. We don't want to wait the full timeout duration I assume?

**Comment by stapelberg** [comment]
It would be good to speed up the test indeed. I suppose we could change kill_timeout via an undocumented config option?

**Comment by orestisf1993** [comment]
How should we detect the closed connection from the test? `read` until we get `-1` as a return value?

**Comment by stapelberg** [comment]
> How should we detect the closed connection from the test? read until we get -1 as a return value?

Yes, that seems like the correct approach to me.

**Comment by orestisf1993** [comment]
No error actually, just 0 returned on EOF, otherwise it would block.

I added the config directive. Should we find a way to hide it in the help message? Maybe ignore those that start with `_`?

```
ERROR: CONFIG: Expected one of these tokens: <end>, '#', 'set ', 'set	', 'set_from_resource', 'bindsym', 'bindcode', 'bind', 'bar', 'font', 'mode', 'floating_minimum_size', 'floating_maximum_size', 'floating_modifier', 'default_orientation', 'workspace_layout', 'default_border', 'new_window', 'default_floating_border', 'new_float', 'hide_edge_borders', 'for_window', 'assign', 'no_focus', 'focus_follows_mouse', 'mouse_warping', 'focus_wrapping', 'force_focus_wrapping', 'force_xinerama', 'force-xinerama', 'disable_randr15', 'disable-randr15', 'workspace_auto_back_and_forth', 'fake_outputs', 'fake-outputs', 'force_display_urgency_hint', 'focus_on_window_activation', 'show_marks', 'workspace', 'ipc_socket', 'ipc-socket', 'ipc_connection_timeout', 'restart_state', 'popup_during_fullscreen', 'exec_always', 'exec', 'client.background', 'client.focused_inactive', 'client.focused', 'client.unfocused', 'client.urgent', 'client.placeholder'
```

**Comment by orestisf1993** [comment]
We should probably also update the documentation.

**Comment by stapelberg** [comment]
Let’s just expose it in the error message, and not make it start with a `_`. That way, we can bless it as supported if the need arises, without having to support two forms.

**Comment by orestisf1993** [comment]
Ok, waiting for your review.

Do you think we should add the queue information in the documentation? The current page doesn't include lots of implementation details.

**Comment by stapelberg** [comment]
Cool, let’s give this a shot! Thanks for your work on this!

**Comment by orestisf1993** [comment]
Thanks for your review too!
